baseURL: "https://wangweiyi-wwyz.github.io/"
languageCode: en-us
build:
  writeStats: true
title: Weiyi Wang | Academic Portfolio
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: aafu

params:
  author: Weiyi Wang
  description: Quantitative finance researcher focusing on machine learning and econometrics.
  copyright: copyright:@2026 Weiyi Wang. All rights reserved.
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: publications
    - item: projects
    - item: skills
      panel_id: skill-panel
    # - item: hobbies
